apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-ingest
  namespace: monitoring
  labels:
    component: elasticsearch
    role: ingest
    k8s-addon: logging-elasticsearch.addons.k8s.io
    k8s-app: elasticsearch-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: ingest
        k8s-app: elasticsearch-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: elasticsearch-logging
      initContainers:  
      - name: init-sysctl      
        image: busybox           
        imagePullPolicy: IfNotPresent             
        command: ["sysctl", "-w", "vm.max_map_count=262144"]  
        securityContext:         
          privileged: true       
      containers:
      - name: elasticsearch-ingest             
        securityContext:         
          capabilities:         
            add:
              - IPC_LOCK
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
        env:                     
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: "tstesdb"
        - name: NODE_NAME
          value: "ingest"
        - name: NETWORK_HOST 
          value: "_eth0_"
        - name: ES_JAVA_OPTS      
          value: -Xms512m -Xmx512m
        - name: MAX_LOCAL_STORAGE_NODES
          value: "1"
        - name: HTTP_ENABLE
          value: "true"
        - name: HTTP_HOST
          value: "localhost"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            cpu: 0.10
          limits:
            cpu: 0.80
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-logging-ingestnode
          mountPath: /data
        - name: elasticsearch-logging-usr-ingestnode
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-config-volume
          mountPath: /usr/share/elasticsearch/config
      volumes:
      - name: elasticsearch-config-volume
        configMap:
          name: elasticsearch-config
          defaultMode: 420
          items:
          - key: elasticsearch.yml
            path: elasticsearch.yml
      - name: elasticsearch-logging-ingestnode
        persistentVolumeClaim:
          claimName: efs-elasticsearch-data-ingestnode
      - name: elasticsearch-logging-usr-ingestnode
        persistentVolumeClaim:
          claimName: efs-elasticsearch-usr-ingestnode
---
