apiVersion: v1
kind: Service
metadata:
  labels:
    component: kibana
  name: kibana
  namespace: monitoring
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    component: kibana
  type: LoadBalancer
