# create per application / pod
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-elasticsearch-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
